// Code generated by protoc-gen-go.
// source: allocator.proto
// DO NOT EDIT!

/*
Package golligator is a generated protocol buffer package.

It is generated from these files:
	allocator.proto
	mesos.proto

It has these top-level messages:
	SlaveResources
	FrameworkResources
	AddFramework
	RemoveFramework
	ActivateFramework
	DeactivateFramework
	AddSlave
	RemoveSlave
	UpdateSlave
	ActivateSlave
	DeactivateSlave
	UpdateWhitelist
	RequestResources
	UpdateAllocation
	RecoverResources
	ReviveOffers
*/
package golligator

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SlaveResources struct {
	SlaveId          *SlaveID    `protobuf:"bytes,1,req,name=slaveId" json:"slaveId,omitempty"`
	Resources        []*Resource `protobuf:"bytes,2,rep,name=resources" json:"resources,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *SlaveResources) Reset()         { *m = SlaveResources{} }
func (m *SlaveResources) String() string { return proto.CompactTextString(m) }
func (*SlaveResources) ProtoMessage()    {}

func (m *SlaveResources) GetSlaveId() *SlaveID {
	if m != nil {
		return m.SlaveId
	}
	return nil
}

func (m *SlaveResources) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type FrameworkResources struct {
	FrameworkId      *FrameworkID `protobuf:"bytes,1,req,name=frameworkId" json:"frameworkId,omitempty"`
	Resources        []*Resource  `protobuf:"bytes,2,rep,name=resources" json:"resources,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *FrameworkResources) Reset()         { *m = FrameworkResources{} }
func (m *FrameworkResources) String() string { return proto.CompactTextString(m) }
func (*FrameworkResources) ProtoMessage()    {}

func (m *FrameworkResources) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *FrameworkResources) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type AddFramework struct {
	FrameworkId      *FrameworkID      `protobuf:"bytes,1,req,name=frameworkId" json:"frameworkId,omitempty"`
	FrameworkInfo    *FrameworkInfo    `protobuf:"bytes,2,req,name=frameworkInfo" json:"frameworkInfo,omitempty"`
	SlaveResources   []*SlaveResources `protobuf:"bytes,3,rep,name=slaveResources" json:"slaveResources,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *AddFramework) Reset()         { *m = AddFramework{} }
func (m *AddFramework) String() string { return proto.CompactTextString(m) }
func (*AddFramework) ProtoMessage()    {}

func (m *AddFramework) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *AddFramework) GetFrameworkInfo() *FrameworkInfo {
	if m != nil {
		return m.FrameworkInfo
	}
	return nil
}

func (m *AddFramework) GetSlaveResources() []*SlaveResources {
	if m != nil {
		return m.SlaveResources
	}
	return nil
}

type RemoveFramework struct {
	FrameworkId      *FrameworkID `protobuf:"bytes,1,req,name=frameworkId" json:"frameworkId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RemoveFramework) Reset()         { *m = RemoveFramework{} }
func (m *RemoveFramework) String() string { return proto.CompactTextString(m) }
func (*RemoveFramework) ProtoMessage()    {}

func (m *RemoveFramework) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

type ActivateFramework struct {
	FrameworkId      *FrameworkID `protobuf:"bytes,1,req,name=frameworkId" json:"frameworkId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ActivateFramework) Reset()         { *m = ActivateFramework{} }
func (m *ActivateFramework) String() string { return proto.CompactTextString(m) }
func (*ActivateFramework) ProtoMessage()    {}

func (m *ActivateFramework) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

type DeactivateFramework struct {
	FrameworkId      *FrameworkID `protobuf:"bytes,1,req,name=frameworkId" json:"frameworkId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *DeactivateFramework) Reset()         { *m = DeactivateFramework{} }
func (m *DeactivateFramework) String() string { return proto.CompactTextString(m) }
func (*DeactivateFramework) ProtoMessage()    {}

func (m *DeactivateFramework) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

type AddSlave struct {
	SlaveId            *SlaveID              `protobuf:"bytes,1,req,name=slaveId" json:"slaveId,omitempty"`
	SlaveInfo          *SlaveInfo            `protobuf:"bytes,2,req,name=slaveInfo" json:"slaveInfo,omitempty"`
	Total              []*Resource           `protobuf:"bytes,3,rep,name=total" json:"total,omitempty"`
	FrameworkResources []*FrameworkResources `protobuf:"bytes,4,rep,name=frameworkResources" json:"frameworkResources,omitempty"`
	XXX_unrecognized   []byte                `json:"-"`
}

func (m *AddSlave) Reset()         { *m = AddSlave{} }
func (m *AddSlave) String() string { return proto.CompactTextString(m) }
func (*AddSlave) ProtoMessage()    {}

func (m *AddSlave) GetSlaveId() *SlaveID {
	if m != nil {
		return m.SlaveId
	}
	return nil
}

func (m *AddSlave) GetSlaveInfo() *SlaveInfo {
	if m != nil {
		return m.SlaveInfo
	}
	return nil
}

func (m *AddSlave) GetTotal() []*Resource {
	if m != nil {
		return m.Total
	}
	return nil
}

func (m *AddSlave) GetFrameworkResources() []*FrameworkResources {
	if m != nil {
		return m.FrameworkResources
	}
	return nil
}

type RemoveSlave struct {
	SlaveId          *SlaveID `protobuf:"bytes,1,req,name=slaveId" json:"slaveId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RemoveSlave) Reset()         { *m = RemoveSlave{} }
func (m *RemoveSlave) String() string { return proto.CompactTextString(m) }
func (*RemoveSlave) ProtoMessage()    {}

func (m *RemoveSlave) GetSlaveId() *SlaveID {
	if m != nil {
		return m.SlaveId
	}
	return nil
}

type UpdateSlave struct {
	SlaveId          *SlaveID    `protobuf:"bytes,1,req,name=slaveId" json:"slaveId,omitempty"`
	Resources        []*Resource `protobuf:"bytes,2,rep,name=resources" json:"resources,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *UpdateSlave) Reset()         { *m = UpdateSlave{} }
func (m *UpdateSlave) String() string { return proto.CompactTextString(m) }
func (*UpdateSlave) ProtoMessage()    {}

func (m *UpdateSlave) GetSlaveId() *SlaveID {
	if m != nil {
		return m.SlaveId
	}
	return nil
}

func (m *UpdateSlave) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type ActivateSlave struct {
	SlaveId          *SlaveID `protobuf:"bytes,1,req,name=slaveId" json:"slaveId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ActivateSlave) Reset()         { *m = ActivateSlave{} }
func (m *ActivateSlave) String() string { return proto.CompactTextString(m) }
func (*ActivateSlave) ProtoMessage()    {}

func (m *ActivateSlave) GetSlaveId() *SlaveID {
	if m != nil {
		return m.SlaveId
	}
	return nil
}

type DeactivateSlave struct {
	SlaveId          *SlaveID `protobuf:"bytes,1,req,name=slaveId" json:"slaveId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DeactivateSlave) Reset()         { *m = DeactivateSlave{} }
func (m *DeactivateSlave) String() string { return proto.CompactTextString(m) }
func (*DeactivateSlave) ProtoMessage()    {}

func (m *DeactivateSlave) GetSlaveId() *SlaveID {
	if m != nil {
		return m.SlaveId
	}
	return nil
}

type UpdateWhitelist struct {
	Whitelist        []string `protobuf:"bytes,1,rep,name=whitelist" json:"whitelist,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UpdateWhitelist) Reset()         { *m = UpdateWhitelist{} }
func (m *UpdateWhitelist) String() string { return proto.CompactTextString(m) }
func (*UpdateWhitelist) ProtoMessage()    {}

func (m *UpdateWhitelist) GetWhitelist() []string {
	if m != nil {
		return m.Whitelist
	}
	return nil
}

type RequestResources struct {
	FrameworkId      *FrameworkID `protobuf:"bytes,1,req,name=frameworkId" json:"frameworkId,omitempty"`
	Requests         []*Request   `protobuf:"bytes,2,rep,name=requests" json:"requests,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RequestResources) Reset()         { *m = RequestResources{} }
func (m *RequestResources) String() string { return proto.CompactTextString(m) }
func (*RequestResources) ProtoMessage()    {}

func (m *RequestResources) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *RequestResources) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type UpdateAllocation struct {
	FrameworkId      *FrameworkID       `protobuf:"bytes,1,req,name=frameworkId" json:"frameworkId,omitempty"`
	SlaveId          *SlaveID           `protobuf:"bytes,2,req,name=slaveId" json:"slaveId,omitempty"`
	Operations       []*Offer_Operation `protobuf:"bytes,3,rep,name=operations" json:"operations,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *UpdateAllocation) Reset()         { *m = UpdateAllocation{} }
func (m *UpdateAllocation) String() string { return proto.CompactTextString(m) }
func (*UpdateAllocation) ProtoMessage()    {}

func (m *UpdateAllocation) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *UpdateAllocation) GetSlaveId() *SlaveID {
	if m != nil {
		return m.SlaveId
	}
	return nil
}

func (m *UpdateAllocation) GetOperations() []*Offer_Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type RecoverResources struct {
	FrameworkId      *FrameworkID `protobuf:"bytes,1,req,name=frameworkId" json:"frameworkId,omitempty"`
	SlaveId          *SlaveID     `protobuf:"bytes,2,req,name=slaveId" json:"slaveId,omitempty"`
	Filters          *Filters     `protobuf:"bytes,3,opt,name=filters" json:"filters,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RecoverResources) Reset()         { *m = RecoverResources{} }
func (m *RecoverResources) String() string { return proto.CompactTextString(m) }
func (*RecoverResources) ProtoMessage()    {}

func (m *RecoverResources) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *RecoverResources) GetSlaveId() *SlaveID {
	if m != nil {
		return m.SlaveId
	}
	return nil
}

func (m *RecoverResources) GetFilters() *Filters {
	if m != nil {
		return m.Filters
	}
	return nil
}

type ReviveOffers struct {
	FrameworkId      *FrameworkID `protobuf:"bytes,1,req,name=frameworkId" json:"frameworkId,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReviveOffers) Reset()         { *m = ReviveOffers{} }
func (m *ReviveOffers) String() string { return proto.CompactTextString(m) }
func (*ReviveOffers) ProtoMessage()    {}

func (m *ReviveOffers) GetFrameworkId() *FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func init() {
}
